import assert from "node:assert/strict"
import { chromium } from "@playwright/test"

const baseURL = process.env.WEB_TEST_URL || "http://127.0.0.1:5178"
const browser = await chromium.launch({ headless: true })
const password = "Browser-test-password-42!"
try {
    const setup = await browser.newContext()
    const session = await setup.request.get(`${baseURL}/auth/session`)
    assert.equal((await session.json()).signupEnabled, true, "Open-signup tests require SIGNUP_ENABLED=true; use closed-signup-ui.mjs for the default closed mode")
    await setup.close()
    for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
        const page = await browser.newPage({ viewport })
        const email = `browser-${viewport.width}-${Date.now()}@example.com`
        const browserErrors = []
        const privateRequests = []
        page.on("pageerror", error => browserErrors.push(error.message))
        page.on("request", request => { if (/\/api\//.test(request.url())) privateRequests.push(request.url()) })
        await page.goto(baseURL)
        await page.getByRole("heading", { name: "Create your account." }).waitFor()
        await page.waitForURL("**/signup")
        assert.deepEqual(privateRequests, [], "Signed-out pages must not fetch private APIs")
        assert.equal(await page.locator("body").evaluate(el => el.scrollWidth <= innerWidth), true)
        await page.getByLabel("Name", { exact: true }).fill("Browser Viewer")
        await page.getByLabel("Email", { exact: true }).fill(email)
        await page.getByLabel("Password", { exact: true }).fill(password)
        await page.getByLabel("Confirm password", { exact: true }).fill("Different-password!")
        await page.getByRole("button", { name: "Create account", exact: true }).click()
        await page.getByRole("alert").filter({ hasText: "don't match" }).waitFor()
        await page.getByLabel("Confirm password", { exact: true }).fill(password)
        await page.screenshot({ path: `/tmp/web-signup-${viewport.width}.png`, fullPage: true })
        const signupResponse = page.waitForResponse(response => response.url().endsWith("/auth/signup") && response.request().method() === "POST")
        await page.getByRole("button", { name: "Create account", exact: true }).click()
        assert.equal((await signupResponse).status(), 201)
        await page.getByRole("button", { name: "Your account" }).waitFor()
        await page.reload()
        await page.getByRole("button", { name: "Your account" }).click()
        await page.getByText(email, { exact: true }).waitFor()
        await page.getByRole("button", { name: "Sign out", exact: true }).click()
        await page.waitForURL("**/login")
        await page.getByRole("heading", { name: "Welcome back." }).waitFor()
        const session = await page.request.get(`${baseURL}/auth/session`)
        assert.equal((await session.json()).user, null, "Logout revokes the browser session")
        await page.getByLabel("Email", { exact: true }).fill(email)
        await page.getByLabel("Password", { exact: true }).fill("Wrong-password-42!")
        await page.getByRole("button", { name: "Log in", exact: true }).click()
        await page.getByRole("alert").waitFor()
        assert.equal(new URL(page.url()).pathname, "/login")
        await page.screenshot({ path: `/tmp/web-login-${viewport.width}.png`, fullPage: true })
        await page.getByRole("link", { name: "Sign up", exact: true }).click()
        await page.getByLabel("Name", { exact: true }).fill("Duplicate Viewer")
        await page.getByLabel("Email", { exact: true }).fill(email)
        await page.getByLabel("Password", { exact: true }).fill(password)
        await page.getByLabel("Confirm password", { exact: true }).fill(password)
        const duplicateResponse = page.waitForResponse(response => response.url().endsWith("/auth/signup") && response.request().method() === "POST")
        await page.getByRole("button", { name: "Create account", exact: true }).click()
        assert.equal((await duplicateResponse).status(), 409)
        await page.getByRole("alert").waitFor()
        await page.getByRole("link", { name: "Log in", exact: true }).click()
        await page.getByLabel("Email", { exact: true }).fill(email)
        await page.getByLabel("Password", { exact: true }).fill(password)
        const loginResponse = page.waitForResponse(response => response.url().endsWith("/auth/login") && response.request().method() === "POST")
        await page.getByRole("button", { name: "Log in", exact: true }).click()
        assert.equal((await loginResponse).status(), 200)
        await page.getByRole("button", { name: "Your account" }).waitFor()
        await page.goto(`${baseURL}/signup`)
        await page.waitForURL(`${baseURL}/`)
        await page.getByRole("button", { name: "Your account" }).waitFor()
        await page.goto(`${baseURL}/settings`)
        await page.getByRole("heading", { name: "Settings", exact: true }).waitFor()
        assert.equal(await page.locator("body").evaluate(el => el.scrollWidth <= innerWidth), true)
        await page.getByRole("button", { name: "Your account" }).click()
        await page.getByText(email, { exact: true }).waitFor()
        assert.equal(await page.getByRole("button", { name: "Sign out", exact: true }).evaluate(el => el === document.activeElement), true)
        const panel = await page.locator("#account-details").boundingBox()
        assert.ok(panel && panel.x >= 0 && panel.x + panel.width <= viewport.width)
        await page.keyboard.press("Escape")
        assert.equal(await page.locator("#account-details").count(), 0)
        await page.getByRole("button", { name: "Your account" }).click()
        await page.getByRole("button", { name: "Sign out", exact: true }).click()
        await page.getByRole("heading", { name: "Welcome back." }).waitFor()
        await page.reload()
        await page.getByRole("heading", { name: "Welcome back." }).waitFor()
        assert.deepEqual(browserErrors, [], "No uncaught browser exceptions")
        await page.close()
    }
    const google = await browser.newPage()
    await google.route("**/auth/session", route => route.fulfill({ json: { configured: true, signupEnabled: true, user: null } }))
    await google.goto(`${baseURL}/login`)
    await google.getByRole("button", { name: "Continue with Google" }).waitFor()
    await google.route("**/auth/google", route => route.fulfill({ contentType: "text/html", body: "<h1>Google authorization redirect</h1>" }))
    await google.getByRole("button", { name: "Continue with Google" }).click()
    await google.waitForURL("**/auth/google")
    await google.goto(`${baseURL}/login?auth_error=account_exists`)
    await google.getByRole("alert").filter({ hasText: "sign in with your password" }).waitFor()
    await google.unroute("**/auth/session")
    await google.route("**/auth/session", route => route.fulfill({ status: 503, body: "Unavailable" }))
    await google.goto(`${baseURL}/login`)
    await google.getByRole("button", { name: "Try again" }).waitFor()
    await google.unroute("**/auth/session")
    await google.route("**/auth/session", route => route.fulfill({ json: { configured: false, signupEnabled: true, user: null } }))
    await google.getByRole("button", { name: "Try again" }).click()
    await google.getByRole("button", { name: "Log in", exact: true }).waitFor()
    assert.equal(await google.getByRole("button", { name: "Continue with Google" }).count(), 0)
    await google.close()
    console.log("Desktop/mobile actual API checks passed: signup, confirmation, duplicate email, invalid password, login, session persistence, logout, auth redirects, private API gate, account menu and responsive layout.")
} finally {
    await browser.close()
}
