import { test, expect } from '@playwright/test'
import { fixtures, active, quality } from './quality-fixtures'

test('only decoded resolutions appear, Auto chooses the best, and explicit quality preserves position and volume', async ({ page }) => {
    await fixtures(page)
    await page.goto('/watch/movie/100?screeningRoom=1')
    const menu = await quality(page)
    await expect(menu.getByRole('radio', { name: /^1080p/ })).toBeVisible()
    await expect(menu.getByRole('radio', { name: /^720p/ })).toBeVisible()
    await expect(menu.getByRole('radio', { name: /^2160p/ })).toHaveCount(0)
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /moviesapi/)
    await expect(menu.getByRole('radio', { name: /^Auto/ })).toHaveAttribute('aria-checked', 'true')
    await menu.getByRole('radio', { name: /^720p/ }).click()
    await expect(page.getByRole('button', { name: 'Quality', exact: true })).toBeFocused()
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(720)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.paused)).toBe(false)
    await page.getByRole('slider', { name: 'Volume', exact: true }).fill('0.35')
    await page.getByRole('slider', { name: 'Playback position' }).fill('10')
    const second = await quality(page)
    await second.getByRole('radio', { name: /^1080p/ }).click()
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(1080)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThanOrEqual(9)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.volume)).toBeCloseTo(.35)
    await expect(page.locator('.cinema-video')).toHaveCount(1)
    expect(await page.locator('.cinema-quality-probe').count()).toBeLessThanOrEqual(1)
    const finalMenu = await quality(page)
    await expect(finalMenu.getByRole('radio', { name: /^1080p/ })).toBeFocused()
    await page.screenshot({ path: '.local/screenshots/quality-menu-1080.png' })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Quality', exact: true })).toBeFocused()
})

test('Auto recovers from a failed source and removes its unavailable resolutions', async ({ page }) => {
    await fixtures(page)
    await page.goto('/watch/movie/101?screeningRoom=1')
    const menu = await quality(page)
    await expect(menu.getByRole('radio', { name: /^1080p/ })).toBeVisible()
    await expect(menu.getByRole('radio', { name: /^720p/ })).toBeVisible()
    await menu.getByRole('radio', { name: /^Auto/ }).click()
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(1)
    await active(page).evaluate((v: HTMLVideoElement) => { v.src = '/missing.mp4'; v.load() })
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /vidfast/)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(720)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(1)
    const recovered = await quality(page)
    await expect(recovered.getByRole('radio', { name: /^1080p/ })).toHaveCount(0)
    await recovered.getByRole('radio', { name: /^720p/ }).click()
    await active(page).evaluate((v: HTMLVideoElement) => { v.src = '/missing.mp4'; v.load() })
    await expect(page.locator('.cinema-notice')).not.toHaveText('')
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /vidfast/)
})

test('empty results can be retried, background checks stay muted, and episode navigation cancels old checks', async ({ page }) => {
    const state = { working: false }
    await fixtures(page, state)
    await page.goto('/watch/movie/102?screeningRoom=1')
    const menu = await quality(page)
    await expect(menu.getByRole('status')).toContainText('No working video found', { timeout: 45000 })
    await expect(menu.getByRole('radio')).toHaveCount(1)
    state.working = true
    await menu.getByRole('button', { name: 'Check again' }).click()
    await expect(menu.getByRole('radio', { name: /^720p/ })).toBeVisible()
    for (const frame of page.frames()) {
        if (await frame.evaluate(() => window.name).catch(() => '') !== 'screening-room-quality-probe') continue
        expect(await frame.locator('video').evaluate((v: HTMLVideoElement) => v.muted)).toBe(true)
    }
    await page.goto('/watch/movie/103?screeningRoom=1')
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /103/)
    expect(await page.locator('.cinema-quality-probe').count()).toBeLessThanOrEqual(1)
})


test('a fixed resolution stays selected when a better source appears and failure offers Auto without downgrading', async ({ page }) => {
    await fixtures(page)
    await page.goto('/watch/movie/104?screeningRoom=1')
    const first = await quality(page)
    await first.getByRole('radio', { name: /^720p/ }).click()
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(720)
    const menu = await quality(page)
    await expect(menu.getByRole('radio', { name: /^1080p/ })).toBeVisible()
    await expect(menu.getByRole('radio', { name: /^720p/ })).toHaveAttribute('aria-checked', 'true')
    expect(await active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(720)
    await menu.getByRole('radio', { name: /^1080p/ }).click()
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(1080)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(1)
    await active(page).evaluate((v: HTMLVideoElement) => { v.src = '/missing.mp4'; v.load() })
    const failed = await quality(page)
    await expect(failed.getByRole('radio', { name: /^1080p/ })).toHaveCount(0)
    await expect(failed.getByRole('radio', { name: /^720p/ })).toBeVisible()
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /moviesapi/)
    await failed.getByRole('radio', { name: /^Auto/ }).click()
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /vidfast/)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(720)
})


test('lazy provider quality menus are checked and selected without repeatedly restarting video', async ({ page }) => {
    await fixtures(page, { working: true }, true)
    await page.route('https://moviesapi.to/**', route => route.fulfill({ contentType: 'text/html', body: '<video></video>' }))
    await page.goto('/watch/movie/105?screeningRoom=1')
    const menu = await quality(page)
    await expect(menu.getByRole('radio', { name: /^1080p/ })).toBeVisible()
    await expect(menu.getByRole('radio', { name: /^720p/ })).toBeVisible()
    await menu.getByRole('radio', { name: /^1080p/ }).click()
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /vidfast/)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(1080)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(4)
    // A provider preference update must not silently override the selected quality.
    await active(page).evaluate((v: HTMLVideoElement) => { v.src='/720.mp4'; v.play() })
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.videoHeight)).toBe(1080)
    await active(page).evaluate((v: HTMLVideoElement) => { v.src='/missing.mp4'; v.load() })
    const retry = await quality(page)
    await expect(retry.getByRole('radio', { name: /^1080p/ })).toHaveCount(0)
    await retry.getByRole('button', { name: 'Check again' }).click()
    await expect(retry.getByRole('radio', { name: /^1080p/ })).toBeVisible()
    await retry.getByRole('radio', { name: /^1080p/ }).click()
    await expect(page.locator('.cinema-video')).toHaveAttribute('src', /vidfast/)
    await expect.poll(() => active(page).evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(4)
})
